plugins:
  - jekyll-remote-theme
remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: contrast

# Site Settings
locale: en-US
title: "Fred Hutch Biomedical Data Science Wiki"
description: "Collective documentation for Genomics, Bioinformatics and Scientific Computing at the Fred Hutch"
url                      : https://sciwiki.fredhutch.org
baseurl                  : ""
repository               : "FredHutch/wiki"


collections:
  generation:
    output: true
    permalink: /:collection/:path/
  gendemos:
    output: true
    permalink: /:collection/:path/
  scicomputing:
    output: true
    permalink: /:collection/:path/
  contributors:
    output: true
    permalink: /:collection/:path/
  compdemos:
    output: true
    permalink: /:collection/:path/
  scicompannounce:
    output: true
    permalink: /:collection/:path/
  drafts:
    output: true
    permalink: /:collection/:path/


atom_feed:
  path                   : /scicompannounce/ # blank (default) uses feed.xml
search                   :  false #, false (default)
search_full_content      :  false #, false (default)
#Note: Only the first 50 words of a post or page’s body content is added to the Lunr search index. Setting search_full_content to true in your _config.yml will override this and could impact page load performance.
# search_provider          :  google #(default), algolia
# Can use google search, here are instructions: https://mmistakes.github.io/minimal-mistakes/docs/configuration/
google:
  search_engine_id: 008250600098126702450:xciawyvddl8

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-123256805-1

# New as of 8/2019
footer:
  links:
    - label: "See our GitHub Repo"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FredHutch/wiki"
    - label: "Join the Conversation on Slack"
      icon: "fab fa-fw fa-slack"
      url: "https://fhbig.slack.com/"
    - label: "See our Contributors"
      icon: "fas fa-user-edit"
      url: /contributors/
    - label: "Find Training"
      icon: "fas fa-chalkboard-teacher"
      url: "https://www.fredhutch.io/"



# Reading Files
include:
  - _data
  - assets
  - _layouts



# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-last-modified-at


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache


# Defaults
###NOTE:  for sciwiki, share: true will turn on the "Edit this page" function at the bottom of the pages
defaults:
  # _generation
  - scope:
      path: ""
      type: generation
    values:
      layout: single
      toc: true
      toc_label: "On This Page"
      share: true
      sidebar:
        nav: "generation"

  # _gendemos
  - scope:
      path: ""
      type: gendemos
    values:
      layout: single
      toc: true
      toc_label: "On This Page"
      share: true
      sidebar:
        nav: "generation"

# _compdemos
  - scope:
      path: ""
      type: compdemos
    values:
      layout: single
      toc: true
      toc_label: "On This Page"
      share: true
      sidebar:
        nav: "scicomputing"

  # _scicomputing
  - scope:
      path: ""
      type: scicomputing
    values:
      layout: single
      toc: true
      toc_label: "On This Page"
      share: true
      sidebar:
        nav: "scicomputing"

# _contributors
  - scope:
      path: ""
      type: contributors
    values:
      layout: single
      share: false

# _scicompannounce
  - scope:
      path: ""
      type: scicompannounce
    values:
      layout: single
      share: false
      sidebar:
        nav: "scicomputing"

  # _drafts
  - scope:
      path: ""
      type: drafts
    values:
      layout: single
      toc: true
      toc_label: "On This Page"
      share: true

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    access-control-allow-origin: "*"
    Access-Control-Allow_Credentials: "true"
    Access-Control-Allow-Headers: "Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range"
    Access-Control-Allow-Methods: "GET,POST,OPTIONS,PUT,DELETE,PATCH"
    
